# Generated by Django 5.2.4 on 2025-07-07 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(verbose_name='프롬프트')),
                ('original_text', models.TextField(verbose_name='원본 추론 결과')),
                ('edited_text', models.TextField(blank=True, verbose_name='수정된 텍스트')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='생성 시각')),
            ],
        ),
    ]
